default: &default

  # Exception Notifier for Mattermost
  use_exception_notifier: true
  notification_hook_url: "https://chat.dwp.io/hooks/gb1kyjrew7rzbprefke8xwx1bc"
  notification_channel_name: "itapps-bugreports"
  notification_mentions: "@willy.tedjakusuma @fernando.baskoro @kevin.goentoro"
  notification_bot_username: "Dashby Bot"

development: &development
  <<: *default
  use_exception_notifier: false
  oauth: "http://localhost:3001"
  # app_id: "f37039bc9122cdb049d2488e5a3c7aefd002edcde8dbf111459ceb7474472657"
  # app_secret: "0b9716fa88674c14e5d20155ef6799d8e22a2cb8643fb11bbcd25dc91d5179cc"

  customer_api: "https://customertrial.dwp.io/graphql"
  #customer_api: "http://localhost:3000/graphql"
  xcost_api: "https://trialbackend.dwp.io/graphql"

  # Oauth
  # oauth: "http://192.168.1.78:3001/"

test:
  <<: *default

production: &production
  <<: *default
  oauth: "https://auth.dwp.io"
  customer_api: "https://customertrial.dwp.io/graphql"

staging:
  <<: *default